### ISSUE TITLE
Github actions fails even though extension is uploaded

### ISSUE THREAD

**Issue by nicolas377** [MobileFirstLLC/cws-publish#7]
The package works perfectly, but when the extension is uploaded and is sent to review (wasnt instantly approved), the package exits with code 1, which triggers github actions to fail. This isnt a major problem, but it's slightly annoying.

**Comment by nkrusch** [comment]
Hi @nicolas377, I have implemented a fix for this. Upgrade to version `2.0.5-alpha.1` and retry.

If it still does not work correctly after upgrade, please open a new issue.

**Comment by nicolas377** [comment]
Thanks! I'll implement and get back later today!
